name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Node Express Image
      run: |
        docker build -f Dockerfile.express -t ${{ secrets.DOCKER_HUB_USERNAME }}/node_express_app:latest .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/node_express_app:latest

    - name: Build and Push NGINX Image
      run: |
        docker build -f Dockerfile.nginx -t ${{ secrets.DOCKER_HUB_USERNAME }}/nginx_reverse_proxy:latest .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nginx_reverse_proxy:latest
